export { lyrics } from "./endpoints/lyrics"
export { madlibs } from "./endpoints/madlibs"
export { text } from "./endpoints/text"
export { meme } from "./endpoints/meme"
export { reddit } from "./endpoints/reddit"
export { word } from "./endpoints/word"
export {setToken, get} from "./utils/requester"